resources:
  - url: http://127.0.0.1:5000/standalone-schedule-card.js
    type: module
views:
  - cards:
      - type: custom:scheduler-card
        name: Standalone Schedule Card Development
        entity: sun.sun
        test_gui: true
